# Generated by Django 5.2.5 on 2025-09-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('provice', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elmentary', models.CharField(max_length=100)),
                ('highschool', models.CharField(max_length=100)),
                ('tertiary', models.CharField(max_length=100)),
                ('achievements', models.CharField(max_length=100)),
                ('year_graduated', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Familybackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothers_name', models.CharField(max_length=100)),
                ('fathers_name', models.IntegerField(max_length=10)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('guardian', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('student_id', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('time', models.IntegerField(max_length=10)),
                ('room', models.IntegerField(max_length=10)),
                ('units', models.IntegerField(max_length=10)),
            ],
        ),
    ]
