# Generated by Django 5.2.5 on 2025-09-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_adress_education_familybackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='zipcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_graduated',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familybackground',
            name='contact_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='familybackground',
            name='fathers_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student_information',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='room',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='units',
            field=models.IntegerField(),
        ),
    ]
