# Generated by Django 5.2.5 on 2025-09-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_adress_zipcode_alter_education_year_graduated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_information',
            name='student_id',
            field=models.CharField(max_length=10),
        ),
    ]
