# Generated by Django 5.2.5 on 2025-09-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_student_information_student_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familybackground',
            new_name='Family_Background',
        ),
        migrations.RenameModel(
            old_name='TestingDatabase',
            new_name='Testing_Database',
        ),
    ]
