# Generated by Django 5.2.5 on 2025-09-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_rename_familybackground_family_background_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_information',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
