# Generated by Django 5.2.5 on 2025-09-05 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0006_alter_student_information_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_enrollment.student_information'),
        ),
    ]
