# Generated by Django 5.2.5 on 2025-09-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0007_education_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_enrollment.student_information'),
        ),
        migrations.AddField(
            model_name='family_background',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_enrollment.student_information'),
        ),
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_enrollment.student_information'),
        ),
    ]
