# Generated by Django 5.2.5 on 2025-09-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0008_adress_student_family_background_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_information',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
