# Generated by Django 5.2.5 on 2025-09-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0009_alter_student_information_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_information',
            options={'ordering': ['first_name']},
        ),
        migrations.AlterField(
            model_name='student_information',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
    ]
