# Generated by Django 5.2.5 on 2025-09-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0010_alter_student_information_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_information',
            options={'ordering': ['last_name']},
        ),
    ]
