# Generated by Django 5.2.5 on 2025-09-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0011_alter_student_information_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['student']},
        ),
    ]
