# Generated by Django 5.2.5 on 2025-09-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0012_alter_education_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'ordering': ['student']},
        ),
        migrations.AlterModelOptions(
            name='family_background',
            options={'ordering': ['student']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['student']},
        ),
    ]
