# Generated by Django 5.2.5 on 2025-09-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0013_alter_adress_options_alter_family_background_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_code']},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AlterField(
            model_name='student_information',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
