# Generated by Django 5.2.5 on 2025-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0014_alter_subject_options_remove_subject_student_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Family_Background',
            new_name='FamilyBackground',
        ),
        migrations.RenameModel(
            old_name='Student_Information',
            new_name='StudentInformation',
        ),
        migrations.RenameModel(
            old_name='Testing_Database',
            new_name='TestingDatabase',
        ),
        migrations.AlterField(
            model_name='subject',
            name='room',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.TimeField(),
        ),
    ]
