# Generated by Django 5.2.5 on 2025-09-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0015_rename_family_background_familybackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.CharField(max_length=20),
        ),
    ]
