# Generated by Django 5.2.5 on 2025-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0016_alter_subject_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familybackground',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='familybackground',
            name='fathers_contact',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='familybackground',
            name='mothers_contact',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='familybackground',
            name='fathers_name',
            field=models.CharField(max_length=100),
        ),
    ]
