# Generated by Django 5.2.5 on 2025-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0017_remove_familybackground_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinformation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='', max_length=10),
        ),
    ]
