# Generated by Django 5.2.8 on 2025-11-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0018_alter_studentinformation_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='elmentary',
            new_name='elementary',
        ),
        migrations.AlterField(
            model_name='familybackground',
            name='fathers_contact',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='familybackground',
            name='mothers_contact',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='student_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
