# Generated by Django 5.2.8 on 2025-11-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0019_rename_elmentary_education_elementary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familybackground',
            name='fathers_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='familybackground',
            name='mothers_contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentinformation',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
